version: '3'
services:
  meme-database-app:
    build: .
    ports:
      - "3000:3000"
      - "3001:3001"
      - "8000:8000"
    environment:
      - PORT_BACKEND=3000
      - PORT_FRONTEND=3001
      - PORT_AI=8000